export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD';

export const REQUEST_MECHS_PENDING = 'REQUEST_MECHS_PENDING';
export const REQUEST_MECHS_SUCCESS = 'REQUEST_MECHS_SUCCESS';
export const REQUEST_MECHS_FAILED = 'REQUEST_MECHS_FAILED';